platform :ios, '8.0'
target 'UniversalApp' do
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
#pod 'NIMSDK', '~> 3.7.0'
pod 'YTKNetwork'
pod 'SDWebImage', '~>3.8'
pod 'WechatOpenSDK'
pod 'FMDB' , '2.6.2'
pod 'MJExtension' , '3.0.13'
pod 'Reachability' , '3.2.0'
pod 'OpenShare', '~> 0.0'
end
